import localFont from "next/font/local";
import "./globals.css";
import { AnimeProvider } from "../context/animeContext.jsx";
import Preloader from "@/components/Preloader/Preloader";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "WalkWise - Step into comfort zone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AnimeProvider>{children}</AnimeProvider>
      </body>
    </html>
  );
}
